apiVersion: v1
kind: Service
metadata:
  name: secure-cicd-service
spec:
  type: NodePort
  selector:
    app: secure-cicd
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30007
